<#
.SYNOPSIS
  Carlos Writer self-test for a LOCAL model (about 5 minutes).

.DESCRIPTION
  Runs 5 published passages from carlosmoralesjr.com through every action (Proofread,
  Sound like Carlos, More casual, More professional, English->Spanish, and Spanish->English
  on the Spanish result), prints the time for each call, and saves the outputs for review.

  It installs nothing and downloads nothing. It sends text only to Ollama on this computer
  (localhost). If Ollama or the model is missing, it stops and says what to do; the choice
  to install is yours.

  The prompts are the exact ones the extension builds (scripts/selftest-requests.json,
  generated by scripts/build-examples.js). If ..\private\selftest-requests-carlos.json
  exists, it is used by default, so "Sound like Carlos" uses your style guide.

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File .\selftest.ps1
.EXAMPLE
  powershell -ExecutionPolicy Bypass -File .\selftest.ps1 -Model qwen3.5:9b
.EXAMPLE
  powershell -ExecutionPolicy Bypass -File .\selftest.ps1 -StyleGuideFile ..\private\carlos-style-guide.txt
#>
[CmdletBinding()]
param(
  [string]$Model = 'llama3.1:8b',
  [string]$Endpoint = 'http://localhost:11434',
  [string]$Requests = '',
  [string]$StyleGuideFile = '',
  [string]$OutDir = '',
  [int]$TimeoutSec = 300
)

$ErrorActionPreference = 'Stop'
$here = Split-Path -Parent $MyInvocation.MyCommand.Path

if ($Endpoint -notmatch '^http://(localhost|127\.0\.0\.1):\d+/?$') {
  throw "The endpoint must be on this computer (http://localhost:PORT). Got: $Endpoint"
}
$Endpoint = $Endpoint.TrimEnd('/')

if (-not $Requests) {
  $private = Join-Path $here '..\private\selftest-requests-carlos.json'
  if (Test-Path $private) { $Requests = $private } else { $Requests = Join-Path $here 'selftest-requests.json' }
}
if (-not (Test-Path $Requests)) { throw "Request file not found: $Requests" }
if (-not $OutDir) { $OutDir = Join-Path $here ('selftest-out\' + (Get-Date -Format 'yyyyMMdd-HHmmss')) }
New-Item -ItemType Directory -Force -Path (Join-Path $OutDir 'raw') | Out-Null

Add-Type -AssemblyName System.Net.Http
$client = New-Object System.Net.Http.HttpClient
$client.Timeout = [TimeSpan]::FromSeconds($TimeoutSec)

function Invoke-Ollama([string]$Path, $BodyObject) {
  $url = $Endpoint + $Path
  if ($null -ne $BodyObject) {
    $json = $BodyObject | ConvertTo-Json -Depth 20 -Compress
    $content = New-Object System.Net.Http.StringContent($json, [System.Text.Encoding]::UTF8, 'application/json')
    $resp = $client.PostAsync($url, $content).GetAwaiter().GetResult()
  } else {
    $resp = $client.GetAsync($url).GetAwaiter().GetResult()
  }
  $bytes = $resp.Content.ReadAsByteArrayAsync().GetAwaiter().GetResult()
  $text = [System.Text.Encoding]::UTF8.GetString($bytes)
  return [pscustomobject]@{ Status = [int]$resp.StatusCode; Text = $text }
}

function Get-Median([double[]]$Values) {
  if (-not $Values -or $Values.Count -eq 0) { return 0 }
  $s = $Values | Sort-Object
  $n = $s.Count
  if ($n % 2 -eq 1) { return [double]$s[[int][math]::Floor($n / 2)] }
  return ([double]$s[$n / 2 - 1] + [double]$s[$n / 2]) / 2
}

# Same cleanup the extension applies: drop <think> blocks, fences, tags and a "Here is..." preface.
function Clean-Output([string]$Raw) {
  $t = [regex]::Replace($Raw, '(?s)<think>.*?</think>\s*', '')
  $t = $t.Trim()
  $t = [regex]::Replace($t, '(?s)^```[a-zA-Z]*\n(.*?)\n?```$', '$1').Trim()
  $t = [regex]::Replace($t, '(?si)^<(passage|text|result|output)>\s*(.*?)\s*</\1>$', '$2').Trim()
  $t = [regex]::Replace($t, '(?i)^(here(''s| is| are)|sure|certainly|of course|okay|aqu[ií] (est[aá]|tienes|va)|claro)[^\n]{0,120}:[ \t]*\n+', '').Trim()
  return $t
}

# Facts that must survive: numbers (digits only), links, emails, CamelCase product names.
function Get-MissingFacts([string]$Original, [string]$Output) {
  $missing = New-Object System.Collections.Generic.List[string]
  $outDigits = ' ' + ([regex]::Replace($Output, '\D+', ' ')) + ' '
  $outNumbers = @([regex]::Matches($Output, '\d+(?:[.,:/-]\d+)*') | ForEach-Object { $_.Value -replace '\D', '' })
  foreach ($m in [regex]::Matches($Original, '\d+(?:[.,:/-]\d+)*')) {
    $d = $m.Value -replace '\D', ''
    if (($outNumbers -notcontains $d) -and ($outDigits -notlike "* $d *")) { $missing.Add($m.Value) }
  }
  foreach ($m in [regex]::Matches($Original, '\bhttps?://[^\s<>"'')\]]+|[\w.+-]+@[\w-]+(?:\.[\w-]+)+')) {
    $v = $m.Value.TrimEnd('.', ',', ';', ':', '!', '?')
    if (-not $Output.Contains($v)) { $missing.Add($v) }
  }
  foreach ($m in [regex]::Matches($Original, '\b[A-Z][a-z]+[A-Z][A-Za-z]*\b')) {
    if (-not $Output.Contains($m.Value)) { $missing.Add($m.Value) }
  }
  return ($missing | Select-Object -Unique) -join ', '
}

Write-Host ''
Write-Host 'Carlos Writer self-test (local model only)' -ForegroundColor Cyan
Write-Host "Endpoint: $Endpoint   Model: $Model"
Write-Host "Prompts:  $Requests"
Write-Host "Output:   $OutDir"
Write-Host ''

# 1. Is Ollama running, and is the model installed? Nothing is downloaded here.
try { $v = Invoke-Ollama '/api/version' $null } catch { $v = $null }
if ($null -eq $v -or $v.Status -ne 200) {
  Write-Host "Ollama is not answering at $Endpoint." -ForegroundColor Yellow
  Write-Host 'Start the Ollama app (it lives in the system tray), then run this script again.'
  exit 1
}
$version = ($v.Text | ConvertFrom-Json).version
$tags = (Invoke-Ollama '/api/tags' $null).Text | ConvertFrom-Json
$installed = @($tags.models | ForEach-Object { $_.name })
if (($installed -notcontains $Model) -and ($installed -notcontains ($Model + ':latest'))) {
  Write-Host "Ollama $version is running, but the model '$Model' is not installed." -ForegroundColor Yellow
  if ($installed.Count -gt 0) { Write-Host ('Installed models: ' + ($installed -join ', ')) }
  Write-Host 'This script does not download anything. If you decide to install it, run:'
  Write-Host "  ollama pull $Model"
  exit 1
}
Write-Host "Ollama $version is running and '$Model' is installed." -ForegroundColor Green

# 2. Load the exact request bodies. Optionally swap in a different style guide.
$data = Get-Content -Raw -Encoding UTF8 $Requests | ConvertFrom-Json
$guide = $null
if ($StyleGuideFile) {
  $guide = (Get-Content -Raw -Encoding UTF8 $StyleGuideFile).Trim()
  Write-Host "Style guide replaced from: $StyleGuideFile"
}
$passages = @{}
foreach ($p in $data.passages) { $passages[$p.id] = $p.text }

# 3. Warm up: the first call loads the model into GPU memory (cold start).
$warm = [ordered]@{
  model = $Model; stream = $false; think = $false
  messages = @(@{ role = 'user'; content = 'Reply with the single word OK.' })
  options = @{ num_ctx = 8192; num_predict = 8; temperature = 0 }
}
$sw = [System.Diagnostics.Stopwatch]::StartNew()
$w = Invoke-Ollama '/api/chat' $warm
$sw.Stop()
if ($w.Status -ne 200) { Write-Host ("Warm-up failed: HTTP " + $w.Status + " " + $w.Text) -ForegroundColor Red; exit 1 }
$wj = $w.Text | ConvertFrom-Json
$loadS = if ($wj.load_duration) { [math]::Round($wj.load_duration / 1e9, 1) } else { 0 }
Write-Host ("Warm-up (model load + tiny answer): {0:N1} s, of which load {1} s" -f $sw.Elapsed.TotalSeconds, $loadS)
Write-Host ''
Write-Host ('{0,-14} {1,-13} {2,8} {3,8} {4,8}  {5}' -f 'passage', 'action', 'seconds', 'out tok', 'tok/s', 'facts missing')
Write-Host ('-' * 78)

# 4. Run every request.
$rows = New-Object System.Collections.Generic.List[object]
$outputs = @{}
$total = [System.Diagnostics.Stopwatch]::StartNew()
foreach ($r in $data.requests) {
  $body = $r.body
  $body.model = $Model
  $isRoundTrip = $null -ne $r.PSObject.Properties['roundTripOf']
  if ($isRoundTrip) {
    $key = $r.passage + '|' + $r.roundTripOf
    if (-not $outputs.ContainsKey($key)) { continue }
    $body.messages[1].content = $body.messages[1].content.Replace('{{EN2ES_OUTPUT}}', $outputs[$key])
  }
  if ($null -ne $guide) {
    $body.messages[0].content = [regex]::Replace($body.messages[0].content, '(?s)(<style_guide>\n).*?(\n</style_guide>)', { param($m) $m.Groups[1].Value + $guide + $m.Groups[2].Value })
  }
  $sw = [System.Diagnostics.Stopwatch]::StartNew()
  try { $res = Invoke-Ollama '/api/chat' $body } catch { $res = [pscustomobject]@{ Status = 0; Text = $_.Exception.Message } }
  $sw.Stop()
  $secs = [math]::Round($sw.Elapsed.TotalSeconds, 2)
  $safeName = ($r.passage + '-' + $r.action) -replace '[^\w.-]', '_'
  [System.IO.File]::WriteAllText((Join-Path $OutDir ('raw\' + $safeName + '.json')), $res.Text, (New-Object System.Text.UTF8Encoding($false)))
  if ($res.Status -ne 200) {
    Write-Host ('{0,-14} {1,-13} {2,8}  ERROR HTTP {3}' -f $r.passage, $r.action, $secs, $res.Status) -ForegroundColor Red
    $rows.Add([pscustomobject]@{ passage = $r.passage; action = $r.action; seconds = $secs; load_s = ''; prompt_tokens = ''; output_tokens = ''; tokens_per_s = ''; facts_missing = 'ERROR'; output = '' })
    continue
  }
  $j = $res.Text | ConvertFrom-Json
  $out = Clean-Output ([string]$j.message.content)
  $outputs[$r.passage + '|' + $r.action] = $out
  $tps = ''
  if ($j.eval_count -and $j.eval_duration) { $tps = [math]::Round($j.eval_count / ($j.eval_duration / 1e9), 1) }
  $original = $passages[$r.passage]
  $miss = Get-MissingFacts $original $out
  $color = 'Gray'
  if ($miss) { $color = 'Yellow' }
  Write-Host ('{0,-14} {1,-13} {2,8} {3,8} {4,8}  {5}' -f $r.passage, $r.action, $secs, $j.eval_count, $tps, $miss) -ForegroundColor $color
  $loadCall = ''
  if ($j.load_duration) { $loadCall = [math]::Round($j.load_duration / 1e9, 2) }
  $rows.Add([pscustomobject]@{
    passage = $r.passage; action = $r.action; seconds = $secs; load_s = $loadCall
    prompt_tokens = $j.prompt_eval_count; output_tokens = $j.eval_count; tokens_per_s = $tps
    facts_missing = $miss; output = $out
  })
}
$total.Stop()

# 5. Save results for review.
$rows | Select-Object passage, action, seconds, load_s, prompt_tokens, output_tokens, tokens_per_s, facts_missing |
  Export-Csv -NoTypeInformation -Encoding UTF8 (Join-Path $OutDir 'results.csv')

$md = New-Object System.Text.StringBuilder
[void]$md.AppendLine('# Carlos Writer self-test outputs')
[void]$md.AppendLine('')
[void]$md.AppendLine("Model: $Model (Ollama $version) - $(Get-Date -Format 'yyyy-MM-dd HH:mm') - prompts: $Requests")
[void]$md.AppendLine('')
[void]$md.AppendLine('Read each output and ask: are the facts intact, and does it sound like me?')
foreach ($p in $data.passages) {
  [void]$md.AppendLine('')
  [void]$md.AppendLine('## ' + $p.id)
  [void]$md.AppendLine('')
  [void]$md.AppendLine('**Original:** ' + $p.text)
  foreach ($row in ($rows | Where-Object { $_.passage -eq $p.id })) {
    [void]$md.AppendLine('')
    [void]$md.AppendLine('**' + $row.action + '** (' + $row.seconds + ' s' + $(if ($row.facts_missing) { '; check: ' + $row.facts_missing } else { '' }) + '):')
    [void]$md.AppendLine('')
    [void]$md.AppendLine('> ' + (($row.output -split "`n") -join "`n> "))
  }
}
[System.IO.File]::WriteAllText((Join-Path $OutDir 'outputs.md'), $md.ToString(), (New-Object System.Text.UTF8Encoding($false)))

$ok = @($rows | Where-Object { $_.facts_missing -ne 'ERROR' })
$lat = [double[]]@($ok | ForEach-Object { [double]$_.seconds })
$tpsAll = [double[]]@($ok | Where-Object { $_.tokens_per_s -ne '' } | ForEach-Object { [double]$_.tokens_per_s })
Write-Host ('-' * 78)
Write-Host ("Calls: {0}   errors: {1}   total: {2:N0} s" -f $rows.Count, ($rows.Count - $ok.Count), $total.Elapsed.TotalSeconds)
Write-Host ("Median seconds per call: {0:N2}   median output speed: {1:N1} tokens/s" -f (Get-Median $lat), (Get-Median $tpsAll))
foreach ($a in @('proofread', 'carlos', 'casual', 'professional', 'en2es', 'es2en')) {
  $s = [double[]]@($ok | Where-Object { $_.action -eq $a } | ForEach-Object { [double]$_.seconds })
  if ($s.Count -gt 0) { Write-Host ("  {0,-13} median {1:N2} s" -f $a, (Get-Median $s)) }
}
Write-Host ''
Write-Host "Saved: $(Join-Path $OutDir 'outputs.md') and results.csv. Review the outputs before trusting the model." -ForegroundColor Cyan
